name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
          browser: [Electron]
          #[Electron chrome, firefox, edge]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browser }}
        uses: Cypress-io/github-action@v6
        with:
            build: npm run build
            start: npm start
            browser: ${{ matrix.browser }}
            command: npx cypress run --browser ${{ matrix.browser }} --reporter-options reportDir=cypress/reports/${{ matrix.browser }}
    
      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/${{ matrix.browser }}/*.json > cypress/reports/${{ matrix.browser }}/merged-reports.json

      - name: Generate HTML Reports
        run: npx marge cypress/reports/${{ matrix.browser }}/merged-reports.json --reportDir cypress/reports/${{ matrix.browser }} -f "${{ matrix.browser }}-report.html"

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
            name: Cypress HTML Report ${{ matrix.browser }}
            path: cypress/reports/${{ matrix.browser }}
         
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if  : failure()
        with:
         name: cypress-screenshots
         path: cypress/screenshots

        